### ISSUE TITLE
Can I get the format of (N,44,3) keypoints?

### ISSUE THREAD

**Issue by Realdr4g0n** [nkolot/ProHMR#2]
Hello thanks for sharing your code.
Can I get the keypoint format for (N,44,3) keypoints?
Or if you have it in your code, I'd really appreciate it if you could tell me where it is.

**Comment by nkolot** [comment]
It actually the first 44 keypoints from SPIN.
The first 25 correspond to the OpenPose keypoints:

OP Nose
OP Neck
OP RShoulder
OP RElbow
OP RWrist
OP LShoulder
OP LElbow
OP LWrist
OP MidHip
OP RHip
OP RKnee
OP RAnkle
OP LHip
OP LKnee
OP LAnkle
OP REye
OP LEye
OP REar
OP LEar
OP LBigToe
OP LSmallToe
OP LHeel
OP RBigToe
OP RSmallToe
OP RHeel

Next we append 19 keypoints from the various datasets we use. There is an overlap between those but we do it because the keypoints are defined slightly differently.

Right Ankle
Right Knee
Right Hip
Left Hip
Left Knee
Left Ankle
Right Wrist
Right Elbow
Right Shoulder
Left Shoulder
Left Elbow
Left Wrist
Neck (LSP)
Top of Head (LSP)
Pelvis (MPII)
Thorax (MPII)
Spine (H36M)
Jaw (H36M)
Head (H36M)

I hope this helps!
